import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import Head from 'next/head'

import withAuthGuard from '../../hocs/withAuthGuard'
import getProduct, { GetProductResponse } from '../../services/products/getProduct'
import useQuery from '../../hooks/useQuery'

const Product: NextPage = () => {
  const router = useRouter()
  const { id: productId } = router.query

  const [productQuery, { data = {}, loading, error }] = useQuery(getProduct)

  const { product } = data as GetProductResponse

  useEffect(() => {
    if (productId) {
      productQuery({ productId })
    }
  }, [productQuery, productId])

  if (error) {
    return <></>
  }

  return (
    <>
      <Head>
        <title>Produto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading ? (
        <>Carregando...</>
      ) : (
        <div className="px-8 pt-8 justify-center">
          {product && (
            <>
              <h3 className="pt-12 text-3xl text-center font-bold">{product.name}</h3>
              <div
                className="p-4 flex flex-col justify-between"
              >
                <div className="mt-4">
                  <p className="text-2xl text-center">Preço: $ {product.price}</p>
                  <div className="mt-8 text-center">
                    <span className="text-xl cursor-pointer">
                      {product.favorite ? '❤️' : '🤍'}
                    </span>
                  </div>
                </div>
              </div>
            </>
          )}
        </div>
      )}
    </>
  )
}

export default withAuthGuard(Product)
