import type { NextPage } from 'next'
import { useEffect, useState } from 'react'
import Head from 'next/head'

import withAuthGuard from '../hocs/withAuthGuard'
import getProducts, { GetProductsResponse } from '../services/products/getProducts'

const Home: NextPage = () => {
  const [currentPage, setCurrentPage] = useState(1)
  const [products, setProducts] = useState([])

  useEffect(() => {
    getProducts({ page: currentPage, perPage: 5 })
      .then((data: GetProductsResponse) => {
        console.log(data)
      })
      .catch((err) => {
        console.log(err)
      })
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        {products.map((product) => (
          <div
            key={`product_${product._id}`}
            className="w-64 m-4 p-4 border border-black rounded-lg"
          >
            <h3 className="text-xl font-weight-bold">{product.name}</h3>
            <p>{product.price}</p>
          </div>
        ))}
      </div>
    </>
  )
}

export default withAuthGuard(Home)
